name: CI

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ main ]
    types: [ opened ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: debug
        run:
          cat /home/runner/.m2/settings.xml

      - name: maven-settings
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "github_1", "username": "dummy", "password": "${MAVEN_TOKEN_REF}"}]'
          githubServer: false

      - name: debug2
        run: |
          cat /home/runner/.m2/settings.xml
          echo "value is: $MAVEN_TOKEN_REF"
        env:
          MAVEN_TOKEN_REF: ${{ secrets.MAVEN_TOKEN }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          MAVEN_TOKEN_REF: ${{ secrets.MAVEN_TOKEN }}

      - name: Discord notification -> success
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "CI"
      - name: Discord notification -> non success
        uses: sarisia/actions-status-discord@v1
        if: ${{ !success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "CI"
